// <auto-generated />
using System;
using IPSUPC.BE.Infraestructure.Persintence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPSUPC.BE.Infraestructure.Migrations
{
    [DbContext(typeof(IPSUPCDbContext))]
    [Migration("20250508033724_LugarConsulta")]
    partial class LugarConsulta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IPSUPC.BE.Transversales.Core.Dias", b =>
                {
                    b.Property<int>("DiaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DiaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiaID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Nombre");

                    b.HasKey("DiaID");

                    b.ToTable("Dias", (string)null);

                    b.HasData(
                        new
                        {
                            DiaID = 1,
                            Code = "LUNES"
                        },
                        new
                        {
                            DiaID = 2,
                            Code = "MARTES"
                        },
                        new
                        {
                            DiaID = 3,
                            Code = "MIÉRCOLES"
                        },
                        new
                        {
                            DiaID = 4,
                            Code = "JUEVES"
                        },
                        new
                        {
                            DiaID = 5,
                            Code = "VIERNES"
                        },
                        new
                        {
                            DiaID = 6,
                            Code = "SÁBADO"
                        },
                        new
                        {
                            DiaID = 7,
                            Code = "DOMINGO"
                        });
                });

            modelBuilder.Entity("IPSUPC.BE.Transversales.Entidades.CitasMedicas", b =>
                {
                    b.Property<int>("CitaMedicaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitaMedicaID"));

                    b.Property<int>("DiaID")
                        .HasColumnType("int");

                    b.Property<int>("EstadoCitaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCita")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorasMedicasID")
                        .HasColumnType("int");

                    b.Property<int>("LugarConsultaID")
                        .HasColumnType("int");

                    b.Property<string>("MedicoID")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PacienteID")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoConsultaID")
                        .HasColumnType("int");

                    b.HasKey("CitaMedicaID");

                    b.HasIndex("DiaID");

                    b.HasIndex("EstadoCitaID");

                    b.HasIndex("HorasMedicasID");

                    b.HasIndex("LugarConsultaID");

                    b.HasIndex("MedicoID");

                    b.HasIndex("PacienteID");

                    b.HasIndex("TipoConsultaID");

                    b.ToTable("CitasMedicas", (string)null);
                });

            modelBuilder.Entity("IPSUPC.BE.Transversales.Entidades.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("IPSUPC.BE.Transversales.Entidades.Medico", b =>
                {
                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NumeroDocumento");

                    b.Property<string>("AnioGraduacion")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("AnioGraduacion");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Celular");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ciudad");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CodigoPostal");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CorreoElectronico");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Departamento");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Direccion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Estado");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("int");

                    b.Property<string>("FechaIngreso")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("FechaIngreso");

                    b.Property<string>("FechaNacimiento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("FechaNacimiento");

                    b.Property<string>("FechaSalida")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("FechaSalida");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LugarNacimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LugarNacimiento");

                    b.Property<string>("MatriculaProfesional")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MatriculaProfesional");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nacionalidad");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Pais");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PrimerApellido");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PrimerNombre");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SegundoApellido");

                    b.Property<string>("SegundoNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SegundoNombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefono");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("Universidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Universidad");

                    b.HasKey("NumeroDocumento");

                    b.HasIndex("EstadoCivil");

                    b.HasIndex("Genero");

                    b.HasIndex("TipoDocumento");

                    b.ToTable("Medicos", "dbo");
                });

            modelBuilder.Entity("IPSUPC.BE.Transversales.Entidades.Pacientes", b =>
                {
                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NumeroDocumento");

                    b.Property<string>("Alergias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Alergias");

                    b.Property<string>("AntecedentesFamiliares")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AntecedentesFamiliares");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Celular");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ciudad");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CodigoPostal");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CorreoElectronico");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Departamento");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Direccion");

                    b.Property<string>("EnfermedadesCronicas")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EnfermedadesCronicas");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Estado");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasMaxLength(10)
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaNacimiento");

                    b.Property<DateTime>("FechaRegistro")
                        .HasMaxLength(10)
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaRegistro");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("GrupoSanguineo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("GrupoSanguineo");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ImagenUrl");

                    b.Property<string>("LugarNacimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LugarNacimiento");

                    b.Property<string>("Medicamentos")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Medicamentos");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nacionalidad");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Pais");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PrimerApellido");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PrimerNombre");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SegundoApellido");

                    b.Property<string>("SegundoNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SegundoNombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefono");

                    b.Property<bool>("TieneAlergias")
                        .HasColumnType("bit")
                        .HasColumnName("TieneAlergias");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.HasKey("NumeroDocumento");

                    b.HasIndex("EstadoCivil");

                    b.HasIndex("Genero");

                    b.HasIndex("TipoDocumento");

                    b.ToTable("Pacientes", "dbo");
                });

            modelBuilder.Entity("IPSUPC.BE.Transversales.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Contrasena");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("Estado");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NombreUsuario");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("NumeroIdentificacion");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("IPSUPC.BE.Transversales.EstadoCita", b =>
                {
                    b.Property<int>("EstadoCitaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoCitaID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Code");

                    b.HasKey("EstadoCitaID");

                    b.ToTable("EstadoCita", (string)null);

                    b.HasData(
                        new
                        {
                            EstadoCitaID = 1,
                            Code = "PENDIENTE"
                        },
                        new
                        {
                            EstadoCitaID = 3,
                            Code = "EN CURSO"
                        },
                        new
                        {
                            EstadoCitaID = 2,
                            Code = "COMPLETADA"
                        },
                        new
                        {
                            EstadoCitaID = 4,
                            Code = "CANCELADA"
                        },
                        new
                        {
                            EstadoCitaID = 5,
                            Code = "NO ASISTIO"
                        });
                });

            modelBuilder.Entity("IPSUPC.BE.Transversales.EstadoCivil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EstadoCivil", "dbo");
                });

            modelBuilder.Entity("IPSUPC.BE.Transversales.Generos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Generos", "dbo");
                });

            modelBuilder.Entity("IPSUPC.BE.Transversales.HorasMedicas", b =>
                {
                    b.Property<int>("HoraMedicaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoraMedicaID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("HoraMedicaID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("HorasMedicas", "dbo");

                    b.HasData(
                        new
                        {
                            HoraMedicaID = 1,
                            Code = "6:00 AM"
                        },
                        new
                        {
                            HoraMedicaID = 2,
                            Code = "6:30 AM"
                        },
                        new
                        {
                            HoraMedicaID = 3,
                            Code = "7:00 AM"
                        },
                        new
                        {
                            HoraMedicaID = 4,
                            Code = "7:30 AM"
                        },
                        new
                        {
                            HoraMedicaID = 5,
                            Code = "8:00 AM"
                        },
                        new
                        {
                            HoraMedicaID = 6,
                            Code = "8:30 AM"
                        },
                        new
                        {
                            HoraMedicaID = 7,
                            Code = "9:00 AM"
                        },
                        new
                        {
                            HoraMedicaID = 8,
                            Code = "9:30 AM"
                        },
                        new
                        {
                            HoraMedicaID = 9,
                            Code = "10:00 AM"
                        },
                        new
                        {
                            HoraMedicaID = 10,
                            Code = "10:30 AM"
                        },
                        new
                        {
                            HoraMedicaID = 11,
                            Code = "11:00 AM"
                        },
                        new
                        {
                            HoraMedicaID = 12,
                            Code = "11:30 AM"
                        },
                        new
                        {
                            HoraMedicaID = 13,
                            Code = "12:00 PM"
                        },
                        new
                        {
                            HoraMedicaID = 14,
                            Code = "12:30 PM"
                        },
                        new
                        {
                            HoraMedicaID = 15,
                            Code = "1:00 PM"
                        },
                        new
                        {
                            HoraMedicaID = 16,
                            Code = "1:30 PM"
                        },
                        new
                        {
                            HoraMedicaID = 17,
                            Code = "2:00 PM"
                        },
                        new
                        {
                            HoraMedicaID = 18,
                            Code = "2:30 PM"
                        },
                        new
                        {
                            HoraMedicaID = 19,
                            Code = "3:00 PM"
                        },
                        new
                        {
                            HoraMedicaID = 20,
                            Code = "3:30 PM"
                        },
                        new
                        {
                            HoraMedicaID = 21,
                            Code = "4:00 PM"
                        },
                        new
                        {
                            HoraMedicaID = 22,
                            Code = "4:30 PM"
                        },
                        new
                        {
                            HoraMedicaID = 23,
                            Code = "5:00 PM"
                        },
                        new
                        {
                            HoraMedicaID = 24,
                            Code = "5:30 PM"
                        },
                        new
                        {
                            HoraMedicaID = 25,
                            Code = "6:00 PM"
                        });
                });

            modelBuilder.Entity("IPSUPC.BE.Transversales.LugarConsulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LugarConsulta", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CONSULTORIO 1 PRIMER PISO"
                        },
                        new
                        {
                            Id = 2,
                            Name = "CONSULTORIO 2 PRIMER PISO"
                        },
                        new
                        {
                            Id = 3,
                            Name = "CONSULTORIO 3 SEGUNDO PISO"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CONSULTORIO 4 SEGUNDO PISO"
                        });
                });

            modelBuilder.Entity("IPSUPC.BE.Transversales.Rol", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "MEDICO"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "PACIENTE"
                        });
                });

            modelBuilder.Entity("IPSUPC.BE.Transversales.TipoConsulta", b =>
                {
                    b.Property<int>("TipoConsultaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TipoConsultaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoConsultaID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Code");

                    b.HasKey("TipoConsultaID");

                    b.ToTable("TipoConsulta", "dbo");

                    b.HasData(
                        new
                        {
                            TipoConsultaID = 1,
                            Code = "ENFERMERÍA"
                        },
                        new
                        {
                            TipoConsultaID = 2,
                            Code = "PSICOLOGÍA"
                        },
                        new
                        {
                            TipoConsultaID = 3,
                            Code = "MEDICINA GENERAL"
                        },
                        new
                        {
                            TipoConsultaID = 4,
                            Code = "ODONTOLOGÍA"
                        });
                });

            modelBuilder.Entity("IPSUPC.BE.Transversales.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TipoDocumento", "dbo");
                });

            modelBuilder.Entity("IPSUPC.BE.Transversales.Entidades.CitasMedicas", b =>
                {
                    b.HasOne("IPSUPC.BE.Transversales.Core.Dias", null)
                        .WithMany()
                        .HasForeignKey("DiaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IPSUPC.BE.Transversales.EstadoCita", null)
                        .WithMany()
                        .HasForeignKey("EstadoCitaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IPSUPC.BE.Transversales.HorasMedicas", null)
                        .WithMany()
                        .HasForeignKey("HorasMedicasID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IPSUPC.BE.Transversales.LugarConsulta", null)
                        .WithMany()
                        .HasForeignKey("LugarConsultaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IPSUPC.BE.Transversales.Entidades.Medico", null)
                        .WithMany()
                        .HasForeignKey("MedicoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IPSUPC.BE.Transversales.Entidades.Pacientes", null)
                        .WithMany()
                        .HasForeignKey("PacienteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IPSUPC.BE.Transversales.TipoConsulta", null)
                        .WithMany()
                        .HasForeignKey("TipoConsultaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IPSUPC.BE.Transversales.Entidades.Medico", b =>
                {
                    b.HasOne("IPSUPC.BE.Transversales.EstadoCivil", null)
                        .WithMany()
                        .HasForeignKey("EstadoCivil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IPSUPC.BE.Transversales.Generos", null)
                        .WithMany()
                        .HasForeignKey("Genero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IPSUPC.BE.Transversales.TipoDocumento", null)
                        .WithMany()
                        .HasForeignKey("TipoDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IPSUPC.BE.Transversales.Entidades.Pacientes", b =>
                {
                    b.HasOne("IPSUPC.BE.Transversales.EstadoCivil", null)
                        .WithMany()
                        .HasForeignKey("EstadoCivil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IPSUPC.BE.Transversales.Generos", null)
                        .WithMany()
                        .HasForeignKey("Genero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IPSUPC.BE.Transversales.TipoDocumento", null)
                        .WithMany()
                        .HasForeignKey("TipoDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IPSUPC.BE.Transversales.Entidades.Usuario", b =>
                {
                    b.HasOne("IPSUPC.BE.Transversales.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
